{{- $rolloutZones := list (dict "name" "" "nodeSelector" (dict)) -}}
{{- if .Values.store_gateway.rollout_operator.enabled -}}
{{- $rolloutZones = .Values.store_gateway.rollout_operator.zones }}
{{- end -}}
{{- range $idx, $rolloutZone := $rolloutZones }}
{{- with $ -}}
{{- $_ := set . "rolloutZone" $rolloutZone -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir.storeGatewayZonename" . }}
  labels:
    {{- include "mimir.labels" (dict "ctx" . "component" "store-gateway" "memberlist" true) | nindent 4 }}
  annotations:
    {{- toYaml .Values.store_gateway.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "mimir.serverHttpListenPort" . }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: {{ include "mimir.serverGrpcListenPort" . }}
      protocol: TCP
      name: grpc
      targetPort: grpc
  selector:
    {{- include "mimir.storeGatewayZoneSelectorLabels" . | nindent 4 }}

---
{{- end -}}
{{- end -}}
