{{- $rolloutZones := list (dict "name" "" "nodeSelector" (dict)) -}}
{{- if .Values.ingester.rollout_operator.enabled -}}
{{- $rolloutZones = .Values.ingester.rollout_operator.zones }}
{{- end -}}
{{- range $idx, $rolloutZone := $rolloutZones }}
{{- with $ -}}
{{- $_ := set . "rolloutZone" $rolloutZone -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir.ingesterZonename" . }}
  labels:
    {{- include "mimir.ingesterZoneLabels" . | nindent 4 }}
    {{- with .Values.ingester.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.ingester.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "mimir.serverHttpListenPort" .}}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: {{ include "mimir.serverGrpcListenPort" . }}
      protocol: TCP
      name: grpc
      targetPort: grpc
  selector:
    {{- include "mimir.ingesterZoneSelectorLabels" . | nindent 4 }}

---
{{- end -}}
{{- end -}}
